version: 2
jobs:
  site:
    docker:
      - image: quay.io/workspace7/antora
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Generate Documentation
          command: |
            export DOC_GEN=[ $(git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i "#doc" | wc -l) -gt 0 ]
            echo $DOC_GEN >> conditional_env_vars.sh
            echo "source conditional_env_vars.sh" >> $BASH_ENV
            if [ $DOC_GEN -ge 1 ]; then 
              git config credential.helper 'cache --timeout=120'
              git config user.name "$GH_USERNAME"
              git config user.email "$GH_EMAIL"
              git checkout -b gh-pages
              antora generate --pull --stacktrace site-gh-pages.yml
              shopt -s extglob 
              rm -vrf !("site") 
              mv site/* . && rm -rf site
              touch .nojekyll
              git add .
              git commit -m "generated documentation"
              git push --force -q https://${GH_TOKEN}@github.com/kameshsampath/openshift-hybridizer.git gh-pages
            fi
workflows:
  version: 2
  generate_site:
    jobs:
      - site:
          filters:
            branches:
              ignore:
                - "gh-pages"
